ljdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/$', 'main.views.index'),
    url(r'^$', 'main.views.index'),
]

main/models.py
#!/usr/bin/python
#encoding=utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf8')
from django.db import models

# Create your models here.

TYPE_CHOICES= (('r','房源数'),('d','成交量'),('nc','新增客源'),('nh','新增房源'),('ns','带看量'),('mnc','月新增客源'),('mnh','月新增房源'),('mns','月带看量'),("td","历史总成交") )
CITY_CHOICES = (('bj','BeiJing'),('sh','ShangHai'))
class City(models.Model):  
    name = models.CharField(max_length=200)  
    def __unicode__(self):  
        return self.name  

class TotalPerDay(models.Model):  
    value = models.CharField(max_length=20)  
    created_at = models.DateTimeField(auto_now=True)  
    city = models.ForeignKey(City) 
    def __unicode__(self):  
        return self.value 

class MSummary(models.Model):
    value =  models.CharField(max_length=500,null=True)
    datetime =  models.DateField()
    city = models.CharField(max_length=20,choices=CITY_CHOICES)
    created_at = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return self.value

class Data(models.Model):
    city = models.CharField(max_length=20,choices=CITY_CHOICES)
    vtype =  models.CharField(max_length=20,choices=TYPE_CHOICES) 
    value = models.IntegerField()
    datetime =  models.DateField()
    created_at = models.DateTimeField(auto_now=True)
    desc1 =  models.CharField(max_length=200,null=True)
    def __unicode__(self):
        return self.vtype + ' ' + str(self.value) + '         ' + str(self.created_at) 
     

main/views.py
from django.shortcuts import render
from models import *
from django.shortcuts import render_to_response
# Create your views here.
vtype_des = {'r':"res"}
def index(request): 
    vtype = request.GET.get('vtype')
    if vtype == 'ms':
	data_list = MSummary.objects.order_by('-created_at') 
        return   render_to_response('index.html',{'m_sums': data_list})
    else:
    	data_list = Data.objects.filter(vtype=vtype).order_by('-created_at')  
        return   render_to_response('index.html',{'r_data_list': data_list,"vtype_des":vtype_des}) 

main/templates/index.html
<style>

body {
    width: 600px;
    margin: 40px auto;
    font-family: 'trebuchet MS', 'Lucida sans', Arial;
    font-size: 14px;
    color: #444;
}

table {
    *border-collapse: collapse; /* IE7 and lower */
    border-spacing: 0;
    width: 100%;    
}

.bordered {
    border: solid #ccc 1px;
    -moz-border-radius: 6px;
    -webkit-border-radius: 6px;
    border-radius: 6px;
    -webkit-box-shadow: 0 1px 1px #ccc; 
    -moz-box-shadow: 0 1px 1px #ccc; 
    box-shadow: 0 1px 1px #ccc;         
}

.bordered tr:hover {
    background: #fbf8e9;
    -o-transition: all 0.1s ease-in-out;
    -webkit-transition: all 0.1s ease-in-out;
    -moz-transition: all 0.1s ease-in-out;
    -ms-transition: all 0.1s ease-in-out;
    transition: all 0.1s ease-in-out;     
}    
    
.bordered td, .bordered th {
    border-left: 1px solid #ccc;
    border-top: 1px solid #ccc;
    padding: 10px;
    text-align: left;    
}

.bordered th {
    background-color: #dce9f9;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#ebf3fc), to(#dce9f9));
    background-image: -webkit-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:    -moz-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:     -ms-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:      -o-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:         linear-gradient(top, #ebf3fc, #dce9f9);
    -webkit-box-shadow: 0 1px 0 rgba(255,255,255,.8) inset; 
    -moz-box-shadow:0 1px 0 rgba(255,255,255,.8) inset;  
    box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;        
    border-top: none;
    text-shadow: 0 1px 0 rgba(255,255,255,.5); 
}

.bordered td:first-child, .bordered th:first-child {
    border-left: none;
}

.bordered th:first-child {
    -moz-border-radius: 6px 0 0 0;
    -webkit-border-radius: 6px 0 0 0;
    border-radius: 6px 0 0 0;
}

.bordered th:last-child {
    -moz-border-radius: 0 6px 0 0;
    -webkit-border-radius: 0 6px 0 0;
    border-radius: 0 6px 0 0;
}

.bordered th:only-child{
    -moz-border-radius: 6px 6px 0 0;
    -webkit-border-radius: 6px 6px 0 0;
    border-radius: 6px 6px 0 0;
}

.bordered tr:last-child td:first-child {
    -moz-border-radius: 0 0 0 6px;
    -webkit-border-radius: 0 0 0 6px;
    border-radius: 0 0 0 6px;
}

.bordered tr:last-child td:last-child {
    -moz-border-radius: 0 0 6px 0;
    -webkit-border-radius: 0 0 6px 0;
    border-radius: 0 0 6px 0;
}



/*----------------------*/

.zebra td, .zebra th {
    padding: 10px;
    border-bottom: 1px solid #f2f2f2;    
}

.zebra tbody tr:nth-child(even) {
    background: #f5f5f5;
    -webkit-box-shadow: 0 1px 0 rgba(255,255,255,.8) inset; 
    -moz-box-shadow:0 1px 0 rgba(255,255,255,.8) inset;  
    box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;        
}

.zebra th {
    text-align: left;
    text-shadow: 0 1px 0 rgba(255,255,255,.5); 
    border-bottom: 1px solid #ccc;
    background-color: #eee;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#f5f5f5), to(#eee));
    background-image: -webkit-linear-gradient(top, #f5f5f5, #eee);
    background-image:    -moz-linear-gradient(top, #f5f5f5, #eee);
    background-image:     -ms-linear-gradient(top, #f5f5f5, #eee);
    background-image:      -o-linear-gradient(top, #f5f5f5, #eee); 
    background-image:         linear-gradient(top, #f5f5f5, #eee);
}

.zebra th:first-child {
    -moz-border-radius: 6px 0 0 0;
    -webkit-border-radius: 6px 0 0 0;
    border-radius: 6px 0 0 0;  
}

.zebra th:last-child {
    -moz-border-radius: 0 6px 0 0;
    -webkit-border-radius: 0 6px 0 0;
    border-radius: 0 6px 0 0;
}

.zebra th:only-child{
    -moz-border-radius: 6px 6px 0 0;
    -webkit-border-radius: 6px 6px 0 0;
    border-radius: 6px 6px 0 0;
}

.zebra tfoot td {
    border-bottom: 0;
    border-top: 1px solid #fff;
    background-color: #f1f1f1;  
}

.zebra tfoot td:first-child {
    -moz-border-radius: 0 0 0 6px;
    -webkit-border-radius: 0 0 0 6px;
    border-radius: 0 0 0 6px;
}

.zebra tfoot td:last-child {
    -moz-border-radius: 0 0 6px 0;
    -webkit-border-radius: 0 0 6px 0;
    border-radius: 0 0 6px 0;
}

.zebra tfoot td:only-child{
    -moz-border-radius: 0 0 6px 6px;
    -webkit-border-radius: 0 0 6px 6px
    border-radius: 0 0 6px 6px
}
  
</style>

<title>北京二手房数据</title>
<a href="/index?vtype=r">房源总数</a>
<a href="/index?vtype=td">成交总数</a>
<a href="/index?vtype=nc">新客源</a>
<a href="/index?vtype=nh">新房源</a>
<a href="/index?vtype=ns">带看量</a>
<a href="/index?vtype=d">成交量</a>
<a href="/index?vtype=mnc">月新客源</a>
<a href="/index?vtype=mnh">月新房源</a>
<a href="/index?vtype=mns">月带看量</a>
<a href="/index?vtype=ms">月汇总</a>

{% if r_data_list %}  

<table class="bordered">
    <thead>
    <tr>
        <th>类型</th>        
        <th>数值</th>
        <th>日期</th>
        <th>添加时间</th>
    </tr>
    </thead>
{% for r in r_data_list %}
    <tr>
        <td>{{r.get_vtype_display}}</td>        
        <td>{{r.value}}</td>
        {% if r.vtype == "mnc" or  r.vtype == "mnh" or  r.vtype ==  "mns" %}
            <td>{{ r.datetime | date:"Y-m"}}</td>
        {% else %}
            <td>{{ r.datetime | date:"Y-m-d"}}</td>
        {% endif %}
        <td>{{ r.created_at | date:"Y-m-d H:i:s" }}</td>
    </tr>        
{% endfor %}
</table>

{% else %}  
<!--<p>No data are available.</p> --> 
{% endif %} 

{% if m_sums %}
<table class="bordered">
    <thead>
    <tr>
        <th>信息</th>
        <th>日期</th>
        <th>添加时间</th>
    </tr>
    </thead>
{% for r in m_sums %}
    <tr>
        <td>{{r.value}}</td>
        <td>{{ r.datetime | date:"Y-m"}}</td>
        <td>{{ r.created_at | date:"Y-m-d H:i:s" }}</td>
    </tr>
{% endfor %}
</table>
{% endif %} 

<p>数据来自小绿中介和建委</p>
<p>推荐shadowsocks,花点小钱远离封锁，拥抱互联网,下载地址：<a href="https://portal.shadowsocks.com.hk/aff.php?aff=4105">点我</a></p>
<a href="mailto:williamwangz@foxmail.com">联系作者</a>